const guestList = new Set()
guestList.add('Alice').add('Bob').add('Charlie').add('David').add('Emma')
guestList.delete('David')
console.log(guestList.has('Alice'))
console.log(guestList.has('David'))
console.log(guestList.size)
guestList.clear()
console.log(guestList.size)

const menu = new Map()
menu.set('Pizza', 12)
menu.set('Burger', 10)
menu.set('Pasta', 15)
menu.set('Salad', 8)
menu.set('Soup', 7)
menu.forEach((price, dish) => console.log(dish, price))
console.log(menu.get('Pasta'))
menu.delete('Soup')
console.log(menu.size)
menu.clear()
console.log(menu.size)

const bankVault = new WeakMap()
let box1 = {}, box2 = {}, box3 = {}, box4 = {}, box5 = {}
bankVault.set(box1, 'Gold')
bankVault.set(box2, 'Documents')
bankVault.set(box3, 'Cash')
bankVault.set(box4, 'Jewelry')
bankVault.set(box5, 'Crypto Keys')
console.log(bankVault.get(box1))
console.log(bankVault.get(box5))
console.log(bankVault.has(box3))
bankVault.delete(box3)
console.log(bankVault.has(box3))

const coinCollection = new WeakSet()
let coin1 = {}, coin2 = {}, coin3 = {}, coin4 = {}, coin5 = {}
coinCollection.add(coin1).add(coin2).add(coin3).add(coin4).add(coin5)
console.log(coinCollection.has(coin1))
console.log(coinCollection.has({}))
coinCollection.delete(coin1)
console.log(coinCollection.has(coin1))
